config/routes.rb
Rails.application.routes.draw do
  
  resources :cities
  devise_for :users, skip: :registrations
  resources :students
  resources :teams
  resources :users
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API
  post "api/v1/authenticate" => "api/version1#authenticate"
  get "api/v1/teams" => "api/version1#get_teams"
  get "api/v1/students" => "api/version1#get_students"
  get "api/v1/cities" => "api/version1#get_cities"
  get "api/v1/team_details/:team_id" => "api/version1#get_team_details"
end

app/models/student.rb
class Student < ApplicationRecord
	after_save :create_user

	validates :student_name, presence: true, uniqueness: true
	validates :phone_no, presence: true

	belongs_to :team

	has_attached_file :photo1,
	:styles => {:medium => "200x200>", :thumb => "80x80>" },
	:default_url => "logo.png",
	:path => ":rails_root/public/sample_app_images/students/:attachment/:id/:style/:filename",
	:url => "/sample_app_images/students/:attachment/:id/:style/:filename"

	validates_attachment :photo1,
	# :presence => true,
	:content_type => { :content_type => ["image/jpg","image/jpeg", "image/gif", "image/png"] },
	:size => { :less_than => 2.4.megabytes, :message => "is over 2.4MB. Please choose another file."}


	def create_user
  		 User.create(user_name: self.student_name, email: self.email, phone_no: self.phone_no, password: "123456") unless User.exists?(email: self.email)
  	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:student_name, :team_id, :phone_no, :photo1)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student, html: { multipart: true , class: 'form-horizontal'} do |f| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td><%= f.label :student_name %></td>
      <td><%= f.text_field :student_name %></td>
    </tr>
    <tr>
      <td><%= f.label :team_id %></td>
      <td><%= f.select("team_id", Team.all.collect {|x| [x.team_name, x.id] }, {include_blank: "Choose Team"}) %></td>
    </tr>
    <tr>
      <td><%= f.label :phone_no %></td>
      <td><%= f.text_field :phone_no %></td>
    </tr>
    <tr>
      <td><%= f.label :photo1 %></td>
      <td><%= f.file_field :photo1, :class => 'form-control' %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit %></td>
    </tr>
  </table>

<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Student name</th>
      <th>Team</th>
      <th>Phone no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.student_name %></td>
        <td><%= student.team.team_name %></td>
        <td><%= student.phone_no %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student name:</strong>
  <%= @student.student_name %>
</p>

<p>
  <strong>Team:</strong>
  <%= @student.team.team_name %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @student.phone_no %>
</p>
<p>
  <%- unless @student.photo1.url == 'logo.png' -%>
    <a href="<%= @student.photo1.url(:original) %>" target="_blank">
      <%= image_tag @student.photo1.url(:medium), class: "col-md-4, col-md-4 col-sm-4"%>
    </a>
  <%- end -%>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>