config/routes.rb
Rails.application.routes.draw do
  
  resources :cities
  devise_for :users, skip: :registrations
  resources :students
  resources :teams
  resources :users
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API
  post "api/v1/authenticate" => "api/version1#authenticate"
  get "api/v1/teams" => "api/version1#get_teams"
  get "api/v1/students" => "api/version1#get_students"
  get "api/v1/cities" => "api/version1#get_cities"
  get "api/v1/team_details/:team_id" => "api/version1#get_team_details"
end

app/models/city.rb
class City < ApplicationRecord
	validates :title, presence: true, uniqueness: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:title, :description, :images)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_form.html.erb
<%= form_for(city) do |f| %>
  <% if city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td><%= f.label :title %></td>
      <td><%= f.text_field :title %></td>
    </tr>
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_area :description %></td>
    </tr>
    <tr>
      <td><%= f.label :images %></td>
      <td><%= f.text_field :images %></td>
    </tr>
    <tr>
      <td></td>
      <td><%= f.submit %></td>
    </tr>
  </table>

<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cities</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.title %></td>
        <td><%= city.description %></td>
        <td><%= city.images %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form', city: @city %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @city.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @city.description %>
</p>

<p>
  <strong>Images:</strong>
  <%= @city.images %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>