config/routes.rb
Rails.application.routes.draw do
  
  resources :cities
  devise_for :users, skip: :registrations
  resources :students
  resources :teams
  resources :users
  root 'students#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # API
  post "api/v1/authenticate" => "api/version1#authenticate"
  get "api/v1/teams" => "api/version1#get_teams"
  get "api/v1/students" => "api/version1#get_students"
  get "api/v1/cities" => "api/version1#get_cities"
  get "api/v1/team_details/:team_id" => "api/version1#get_team_details"
end

app/views/layouts/_custom_menu.html.erb
<table>
	<tr class="nav">
		<td><%= link_to "User", users_path, class: "" %></td>
		<td><%= link_to "Team", teams_path, class: "" %></td>
		<td><%= link_to "Student", students_path, class: "" %></td>
		<td><%= link_to "City", cities_path, class: "" %></td>
		<td><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></td>
	</tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%- if user_signed_in? -%>
      <%= render :partial => 'layouts/custom_menu' %>
      <div  class="col-lg-12 col-md-12">
    <%- end -%>
  	<% if notice || params[:notice] %>
      <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= notice || params[:notice]%>
      </div>
    <% end %>
    
    <%= yield %>
  </body>
</html>